version: '3.4'

services:
  configserver:
    environment:
      - spring.cloud.config.git.uri=https://github.com/SteeltoeOSS/Samples/

  musicservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - spring__cloud__config__uri=http://configserver:8888

  shoppingcartservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - spring__cloud__config__uri=http://configserver:8888

  orderservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - spring__cloud__config__uri=http://configserver:8888

  musicstore:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - spring__cloud__config__uri=http://configserver:8888
    ports:
      - "5555:5555"
