apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
spec:
  selector:
    matchLabels:
      app: sqlserver
  replicas: 1
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "SteeltoeR0cks!"
---
apiVersion: v1
kind: Service
metadata:
  name: sqlserver
spec:
  ports:
  - port: 1433
  selector:
    app: sqlserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eurekaserver
spec:
  selector:
    matchLabels:
      app: eurekaserver
  replicas: 1
  template:
    metadata:
      labels:
        app: eurekaserver
    spec:
      containers:
      - name: eurekaserver
        image: steeltoeoss/eurekaserver
        ports:
        - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eurekaserver
spec:
  ports:
  - port: 8761
  selector:
    app: eurekaserver
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-admin
spec:
  selector:
    matchLabels:
      app: spring-boot-admin
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-boot-admin
    spec:
      containers:
      - name: spring-boot-admin
        image: hananiel/spring-boot-admin-eureka-sample
        ports:
        - containerPort: 8080
        env:
          - name: EUREKA_SERVICE_URL
            value: http://eurekaserver:8761
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-admin
spec:
  ports:
  - port: 8080
  selector:
    app: spring-boot-admin
  type: LoadBalancer
    
    
    
