apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicservice
spec:
  selector:
    matchLabels:
      component: musicservice
  replicas: 1
  template:
    metadata:
      labels:
        app: musicservices
        component: musicservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: musicservice
        image: <acr>/musicservice:<version>
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
        envFrom:
          - configMapRef:
              name: musicconfig
---
apiVersion: v1
kind: Service
metadata:
  name: musicservice
spec:
  ports:
  - port: 80
  selector:
    component: musicservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  selector:
    matchLabels:
      component: orderservice
  replicas: 1
  template:
    metadata:
      labels:
        app: musicservices
        component: orderservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: orderservice
        image: <acr>/orderservice:<version>
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
        envFrom:
          - configMapRef:
              name: musicconfig
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  ports:
  - port: 80
  selector:
    component: orderservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shoppingcartservice
spec:
  selector:
    matchLabels:
      component: shoppingcartservice
  replicas: 1
  template:
    metadata:
      labels:
        app: musicservices
        component: shoppingcartservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: shoppingcartservice
        image: <acr>/shoppingcartservice:<version>
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
        envFrom:
          - configMapRef:
              name: musicconfig
---
apiVersion: v1
kind: Service
metadata:
  name: shoppingcartservice
spec:
  ports:
  - port: 80
  selector:
    component: shoppingcartservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicstore
spec:
  selector:
    matchLabels:
      component: musicstore
  replicas: 1
  template:
    metadata:
      labels:
        app: musicstore
        component: musicstore
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: musicstore
        image: <acr>/musicstore:<version>
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "80"
        envFrom:
          - configMapRef:
              name: musicconfig
---
apiVersion: v1
kind: Service
metadata:
  name: musicstore
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: musicstore
  type: LoadBalancer
