AppSettings:
  SiteTitle: Music Store
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Debug
    System: Information
    Microsoft: Information

eureka:
  client:
    serviceUrl: http://172.30.32.53:8761/eureka/
mysql:
  client:
    server: 172.29.167.57
redis:
  client:
    host: 172.16.94.235